apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: web-content-v3
  namespace: web
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: san
