apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: web-content-v1
  namespace: web
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: nas-silver
