- name: Create a SnapMirror replication relationship
  hosts: localhost
  gather_facts: no
  connection: local

  vars:
    netapp_hostname: 192.168.0.101
    netapp_username: admin
    netapp_password: Netapp1!
  tasks:
     - name: Create SnapMirror
       na_ontap_snapmirror:
         state: present
         destination_volume: trident_default_persistent_volume_claim_dest
         source_vserver: svm1
         destination_vserver: cloud_volumes_ontap
         hostname: "{{ netapp_hostname }}"
         username: "{{ netapp_username }}"
         password: "{{ netapp_password }}"
         https: true
         validate_certs: false
         source_volume: 