kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: persistent-volume-claim-san
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: storage-class-san