apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: nas-gold
provisioner: netapp.io/trident
allowVolumeExpansion: true
parameters:
  backendType: "ontap-nas"
  media: "ssd"
  provisioningType: "thick"
  encryption: "true"
  